AWSTemplateFormatVersion: '2010-09-09'
Description: my-blog S3 + CloudFront

Parameters:
  BlogCertificateArn:
    Type: String
  Domain:
    Type: String

Resources:
  HugoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-my-blog-bucket"
      AccessControl: Private

  HugoCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for my-blog"

  HugoS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HugoS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt HugoCloudFrontOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "${HugoS3Bucket.Arn}/*"
    DependsOn:
      - HugoCloudFrontOAI


  
  HugoCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: HugoS3Origin
            DomainName: !GetAtt HugoS3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", !Ref HugoCloudFrontOAI]]
        DefaultCacheBehavior:
          TargetOriginId: HugoS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref BlogCertificateArn
          SslSupportMethod: sni-only
        Aliases:
        - !Ref Domain
        PriceClass: PriceClass_100

  BlogRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:/route53/blog-hosted-zone-id}}"
      Name: !Ref Domain
      Type: A
      AliasTarget:
        DNSName: !GetAtt HugoCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  
